DROP TABLE person;
CREATE TABLE PERSON (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(255),
    AGE INT
);

INSERT INTO PERSON (NAME, AGE) VALUES ('Mario Rossi', 30);
INSERT INTO PERSON (NAME, AGE) VALUES ('Luigi Bianchi', 25);
